### ISSUE TITLE
MP管理-MP管理页面-详细-关联POP下拉列表显示问题修改

### ISSUE THREAD

**Issue by kimcy99** [imc-ux/AdvancedSvelte#14]
MP管理-MP管理页面-详细-关联POP下拉列表显示问题修改

![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/d890e4d0-2757-4068-a60a-f1ed9f9a02fd)

**Comment by foster7n15** [comment]
2023-10-18

**Comment by kimcy99** [comment]
V1.0.1

**Comment by kimcy99** [comment]
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/081dc3e2-186d-482e-a15c-de6626d702b2)
