### ISSUE TITLE
MP管理-检索页面负责人增加Link

### ISSUE THREAD

**Issue by kimcy99** [imc-ux/AdvancedSvelte#15]
页面负责人，检查负责人，增加Link，Link到用户信息
多用户时，用户信息pop上面加 tab

![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/0cbb295b-0467-49a6-b663-64c819ee39ee)

**Comment by liujinhai8410** [comment]
预计完成日 2023-10-20

**Comment by kimcy99** [comment]
V1.0.1

**Comment by kimcy99** [comment]
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/e1b56234-2af5-4dc2-b940-c6d68b3128ca)

**Comment by foster7n15** [comment]
2023-11-07
