### ISSUE TITLE
MP管理-检索页面 文字显示不完整

### ISSUE THREAD

**Issue by kimcy99** [imc-ux/AdvancedSvelte#17]
MP管理-检索页面 文字显示不完整 （GR Management---g显示不完整）

![2](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/73733f69-0944-4f0f-8301-f23c52249419)

**Comment by liujinhai8410** [comment]
> 预计完成日 2023-10-18

**Comment by kimcy99** [comment]
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/db3ae5d8-f77c-41a0-a319-edf9c54ed641)

**Comment by kimcy99** [comment]
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/24e4433a-e9fb-4430-829a-e27e3c0b53e3)
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/2290e271-1880-4b5c-9e88-0d6b1508dbcd)
