### ISSUE TITLE
上传信息-减小翻页控件显示高度

### ISSUE THREAD

**Issue by kimcy99** [imc-ux/AdvancedSvelte#18]
上传信息-减小翻页控件显示高度

![3](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/3f612e86-1e3c-4089-b684-c7feef4173cf)

**Comment by liujinhai8410** [comment]
> 预计完成日 2023-10-19

**Comment by kimcy99** [comment]
V1.0.1

**Comment by kimcy99** [comment]
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/cbe2b2de-0678-4019-8954-33173a0f978c)
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/d4b23ccf-d6f2-4666-b203-da5b25f13de3)
