### ISSUE TITLE
上传信息-检索页面显示问题修改

### ISSUE THREAD

**Issue by kimcy99** [imc-ux/AdvancedSvelte#20]
上传信息-检索页面显示问题修改
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/9c4f8b71-ef11-4d7b-a7cb-168cf2cae8ec)

**Comment by liujinhai8410** [comment]
> 预计完成日 2023-10-20

**Comment by liujinhai8410** [comment]
预计完成日 2023-11-22
