### ISSUE TITLE
上传信息-查看详细 最后一列缺少竖线

### ISSUE THREAD

**Issue by kimcy99** [imc-ux/AdvancedSvelte#22]
上传信息-查看详细/冲突详细 最后一列缺少竖线
![4](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/ad7095c7-4cd9-47d1-85ef-7822220d9fde)
![5](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/bc03c2af-f0f8-4473-8f54-dca550e95942)

**Comment by liujinhai8410** [comment]
预计完成日 2023-10-20

**Comment by liujinhai8410** [comment]
预计完成日2023-11-21
