### ISSUE TITLE
jtrac detail page delete function error

### ISSUE THREAD

**Issue by wind-in-wind** [imc-ux/AdvancedSvelte#4]
in jtrac detail page,when I perform a deletion operation, an error is reported.
![666](https://github.com/imc-ux/AdvancedSvelte/assets/37617506/b1afc436-62e6-4377-8ac8-ea11210a0880)

**Comment by ythyhvh** [comment]
@liujinhai8410   辛苦确认一下

**Comment by liujinhai8410** [comment]
ok

**Comment by liujinhai8410** [comment]
已完成

**Comment by ythyhvh** [comment]
close
