### ISSUE TITLE
[Input]: 样式变更（UI颜色取主题色）

### ISSUE THREAD

**Issue by kimcy99** [imc-ux/AdvancedSvelte#41]
### Describe the problem

![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/7181a474-dd9c-4a2f-a562-b0939ff7b1a3)
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/92afd399-e890-4057-8df0-5e4e82b52157)

### Describe the proposed solution

样式参考链接
https://sveltematerialui.com/demo/textfield/

![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/d632e88e-0614-442c-9acb-93740055b972)
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/e7085390-0c00-4a45-9b22-9b208d408edd)

### Importance

nice to have

**Comment by Cheesanse** [comment]
计划11月24日完成

**Comment by ythyhvh** [comment]
继续
