### ISSUE TITLE
上传信息-检索页面删除后台负责人和紧急程度

### ISSUE THREAD

**Issue by kimcy99** [imc-ux/AdvancedSvelte#5]
1.  检索页面删除：后台负责人，紧急程度
2.  前台负责人/代码负责人合并一列
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/aca44c74-328a-41b3-8347-66ab263d4157)

**Comment by liujinhai8410** [comment]
预计完成日 2023-10-18

**Comment by kimcy99** [comment]
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/f9c90e5d-8c19-486b-9239-5b6192642c95)
