### ISSUE TITLE
[MP管理]: Type改成多选

### ISSUE THREAD

**Issue by kimcy99** [imc-ux/AdvancedSvelte#53]
### Describe the problem

筛选主页面不方便

### Describe the proposed solution

Type改成多选

### Screenshot

![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/670640db-1f4d-4884-9bf9-1daccc79ef26)

### Importance

nice to have

**Comment by liujinhai8410** [comment]
预计2023-11-21完成
