### ISSUE TITLE
上传信息-检索页面，负责人增加Link

### ISSUE THREAD

**Issue by kimcy99** [imc-ux/AdvancedSvelte#6]
1. 前台负责人，代码检查负责人，增加Link，Link到用户信息
2. 多用户时，用户信息pop上面加 tab

![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/9712bca8-ec1c-4ed0-9f0f-37d5c325fe4b)

**Comment by foster7n15** [comment]
2023-10-18

**Comment by kimcy99** [comment]
需求2.多用户时，用户信息pop上面加 tab 未实现

![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/c8356b3d-8d21-4c3a-9a06-5e489c80e90d)

**Comment by kimcy99** [comment]
切换名字头像不变
![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/372bb809-ba65-42e3-821c-5afcd1a915e6)
