### ISSUE TITLE
上传信息- 检索页面，模块列表增加复制功能

### ISSUE THREAD

**Issue by kimcy99** [imc-ux/AdvancedSvelte#7]
模块列表增加复制功能

![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/c3373893-94fc-4dcb-bb82-d7ca1856b7a7)

**Comment by liujinhai8410** [comment]
预计完成日 2023-10-19

**Comment by liujinhai8410** [comment]
预计完成日 2023-11-21
