### ISSUE TITLE
上传信息-检索页面

### ISSUE THREAD

**Issue by kimcy99** [imc-ux/AdvancedSvelte#9]
出现滚动条时，页面背景显示不完整

![image](https://github.com/imc-ux/AdvancedSvelte/assets/144866073/c3a8c0f6-25b0-411b-9ba3-6e6c4c8451df)

**Comment by liujinhai8410** [comment]
预计完成日 2023-10-24

**Comment by liujinhai8410** [comment]
预计完成日 2023-11-22
